services:
  - type: web
    name: opengeek-community-server
    env: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm cache clean --force && npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: ""
    healthCheckPath: /api/health